language: python
python:
  - "3.9"

install:
  - pip install -r src/tests/unit/requirements.txt

branches:
  only:
  - main
  - dev
  
jobs:
  include:
    - stage: test
      script:
        - pushd src/tests/unit
        - python3 tests_phishing_utils.py
        - popd
