version: '3.8'

services:

  web:
    build: ./src
    command: bash -c "cd krini_web/mock_data && python3 fill_database.py && cd .. && gunicorn --bind 0.0.0.0:5000 run:app --log-file=-"
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    restart: always

volumes:
  data: