version: '3.8'

services:
  web:
    build: ./src
    command: bash -c "pwd && ls -l && cd ./src/krini_web && flask run --host=0.0.0.0 --port=5000"
    volumes:
      - ./src:/usr/src/semisupervised-learning-in-cibersecurity/src
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=krini

volumes:
  postgres_data: