
CREATE TABLE IF NOT EXISTS users (
  userID SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS white_list (
  urlID SERIAL PRIMARY KEY,
  url TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS black_list (
  urlID SERIAL PRIMARY KEY,
  url TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS to_check_list (
  urlID SERIAL PRIMARY KEY,
  url TEXT UNIQUE NOT NULL,
  previous TEXT NOT NULL
);