version: '3.8'

services:
  web:
    image: phf1001/krini:web-v10
    container_name: semisupervised-learning-in-cibersecurity_web
    command: bash -c "cd krini_web/mock_data && python3 fill_database.py && cd .. && gunicorn run:app --bind 0.0.0.0:5000 --preload --workers 4 --timeout 0 --log-file=-"
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=0
      - DATABASE_URL=postgresql://dev:123@db:5432/krini
      - SQL_HOST=db
      - SQL_PORT=5432
      - DATABASE=postgres
    depends_on:
      - db

  db:
    image: phf1001/krini:db-v10
    container_name: semisupervised-learning-in-cibersecurity_db
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=krini

volumes:
  data:
